version: "3"

services:

  fluentd:
    image: fluent/fluentd:v1.7.3-1.0
    user: "${USER_ID}:${GROUP_ID}"
    ports:
      - "${FLUENTD_PORT}:24224"
      - "${FLUENTD_PORT}:24224/udp"
    volumes:
      - ./log:/fluentd/log
    restart: always
    networks:
      bridge:
        ipv4_address: 192.168.0.10

  python:
    image: python:alpine
    logging:
      driver: fluentd
      options:
        tag: "docker.{{.ID}}"
        fluentd-address: 192.168.0.10:24224
    depends_on:
      - fluentd

networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16
